[package]
name = "jsrt"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = []
boa = ["dep:boa_engine"]

[dependencies]
thiserror = { workspace = true }
boa_engine = { version = "0.19", optional = true }

